### ISSUE TITLE
[FRS] Football Introductory Session

### ISSUE THREAD

**Issue by ohhteejayy** [OpenSUTD/DiscoverSUTD-2020#19]
**Football Introductory Session**

Recruitment for SUTD Men's, Women's & Recreational Team!

**Abstract**

Ever wanted to play for SUTD in our annual University Games? Or try out Football as a recreational sport? 
Come down to our Introductory Session to find out more about our Fifth Row!

**Student Organisation organising this Session**

SUTD Football Executive Committee

**Session Intent (What to Expect)**

- Participants will learn about Football as a Fifth Row (i.e. Training Dates, Events, etc.)
- Participants will try their feet at Football as a game.
- NO prior experience with Football required!
- PT attire and covered shoes/boots required.

**Session Details**

2000hrs to 2200hrs, 17th of Sep 2020 (Thurs) & 22nd Sep 2020 (Tues) @ SUTD Football Field. 
Able to take up to 40 Freshies per session.
Students will have to fill up our online form to register their interest. If they do not do so, we cannot allow them to join in due to 
the Varsity's Covid-19 measures.

For pre-event, at 1945hrs – 2000hrs, there will be preparation for training.
For post-event, at 2200hrs – 2215hrs, there will be packing up of equipment.

**Speakers/Workshop Facilitators**

Men's and Women's Coach from F17 Academy
Football Executive Committee Members (Sophomores)

**Logistical Details**
Sign-Up form: https://forms.office.com/Pages/ResponsePage.aspx?id=drd2NJDpck-5UGJImDFiPexc6dXf33VDuFGsk8Av6thUMDZNTzU1MElMM0RYODRIVzNHQVdJQjVBRy4u

No budget required.
Club e-mail: football@club.sutd.edu.sg

**Comment by jamestiotio** [comment]
Hi @ohhteejayy! Sounds like a great session. Unfortunately, if you check over at the current [events page](https://discover.opensutd.org/events.html#sutd) (based on our latest schedule), there will be a compulsory Hostel Briefing Session and Hostel Floor Supper organized by SUTD Housing and the House Guardians on the 15th of September 2020, 2000hrs to 2200hrs. They are mandatory for every incoming Freshmore. If you would like to propose another timing, feel free to comment down below or edit your post.

If you edit your post, I will check this issue again in around 2-3 days to give your team some planning time. Alternatively, just mention me in a new comment whenever your team has decided on the new timing. Cheers!

**Comment by ohhteejayy** [comment]
Hey @jamestiotio. Thank you for the prompt. We have changed our date to 17th Sep, Thurs and 22nd Sep, Tues. 
I have updated the post accordingly.

Thank you and do let me know if there is anything out of order.

**Comment by jamestiotio** [comment]
Hi @ohhteejayy, do take note that DiscoverSUTD supper sessions will be [held concurrently](https://discover.opensutd.org/events.html#supper) with your latest timings of the Football Introductory Session. While the supper sessions are not compulsory, this might lead to less-than-expected number of signups for your session.

If your team is okay with that, I will approve this session and add it into the calendar.

**Comment by ohhteejayy** [comment]
Hi @jamestiotio, we would like proceed with the event. Thank you.

**Comment by jamestiotio** [comment]
Alright then. Session approved.

**Comment by jamestiotio** [comment]
@ohhteejayy Do include your signup online form here once it is ready so that we can add it onto the events page.

**Comment by ohhteejayy** [comment]
@jamestiotio We have included the Microsoft form in the "Logistics" section. We have also done up the Declaration of Personal Data Collection with the school and included the clause of acceptance in the form. Thanks.

**Comment by jamestiotio** [comment]
Hi @ohhteejayy, could you copy [this template](https://forms.office.com/Pages/ShareFormPage.aspx?id=drd2NJDpck-5UGJImDFiPbne1iyIR1hKtYGeiPHQbEBUM0JEN0xMN041VFBZOU1aSjRVTzlTMzBISi4u&sharetoken=TEsfn8upjgncvVX6vj8Y) for the sign-up form? You can include your more specific questions in Section 2 under Additional Information.

I will add this session to the calendar and the events page once you have revised the sign-up form.

**Comment by ohhteejayy** [comment]
Hi @jamestiotio, I have tailored the form to your template. Do let me know if anything else is required to be done. Thank you.

**Comment by ohhteejayy** [comment]
Hi @jamestiotio, I have been in discussion with Office of Student Life on the event. Approval for the event will only be given nearer to matriculation week. In that case, advertising for our event can only go ahead after approval is given. I'll keep you posted on any developments. 

OSL has stated that approval for all events (Sports Cluster, that I know of) will be approved only nearer to matriculation. Hope this info will help with your admin. 

Do you mind if we exchange telegram handles for faster communication?

**Comment by jamestiotio** [comment]
@ohhteejayy Ah alright then, thank you for the update. We will await for OSL's approval for the respective introductory events. You can contact me on Telegram [here](https://t.me/jamestiotio).

**Comment by jamestiotio** [comment]
Based on the latest decision by OSL, we will be approving the events conducted under DiscoverSUTD instead. We shall then await the Registrar's directive on the possibility of conducting physical events. I will reopen this issue until we obtain further instructions.

**Comment by jiawei2912** [comment]
**Update - 10 September 2020**
**Session Name:** Recruitment for SUTD Men's, Women's & Recreational Team!
**Status:** Approved
**Allowed Members:** 
- Ong Tao Jie
- Amelia Natasha Yeo Wen Ting
- Rachel Chia
- Mohamad Arshad
- Damian Ong Zhi Sheng
- Lim Ze Li

**Remarks:**
- Nil
