### ISSUE TITLE
[FRS] Introductory Training for Systema (Russian Martial Arts)

### ISSUE THREAD

**Issue by nurulakhra** [OpenSUTD/DiscoverSUTD-2020#30]
**Session Name**

Introductory Training for Systema (Russian Martial Arts)

**Abstract**

Seen our video? Interested to find out more and experience our training? Then come on down for this training! We will be touching mostly on basic drills and simple exercises to get the body moving and for you to first understand the intentions behind our training. This is also an opportunity for you to interact with us and our instructor (an alumni of SUTD and owner of SG Systema), and ask as many questions as you like!

Hope to see you there!!

**Student Organisation organising this Session**

Systema SUTD (Russian Martial Arts)

**Session Intent (What to Expect)**

- Participants will learn more about what Systema is and how we train. 
- No pre-requisites required.
- _Learn the relation between breathing and movements. Understand the body’s alignment. Practice self/situational awareness._

**Session Details**

Number of participants: 12
Venue: Track
Timing: 19:30 to 21:30 on Friday 25 Sept

**Speakers/Workshop Facilitators**

Coach: Lau Wen Hsin 

Wen Hsin is the owner and instructor of SG Systema. He had been to Russia multiple times to train with Daniil Ryabko, son of the founder of Systema - Mikhail Ryabko, where he attained the instructor certification. He has also conducted many workshops under Systema SG with internationally known guest instructors such as Adam and Brandon Zettler, Vladimier Zaikovsky, Roy Onishi and more. He is an alumni of SUTD. 

**Logistical Details**

Help us with the overall resourcing of our events. This will give us some cues on as to how to budget for the event and if there are further constraints that we must consider.

No budget required. 

Please provide us with your club e-mail address so we can notify you once your event has been scheduled.

systema@club.sutd.edusg

If your event is on a sign-up basis, also include your sign-up form link here. Copy [this template](https://forms.office.com/Pages/ShareFormPage.aspx?id=drd2NJDpck-5UGJImDFiPbne1iyIR1hKtYGeiPHQbEBUM0JEN0xMN041VFBZOU1aSjRVTzlTMzBISi4u&sharetoken=TEsfn8upjgncvVX6vj8Y) to ensure consistent branding throughout DiscoverSUTD.

https://forms.office.com/Pages/ResponsePage.aspx?id=drd2NJDpck-5UGJImDFiPWs5dGc3WjVLs4KtG2NFLnJUNVZDQUczTDJXU0hWT1BJSlZTS0NRNUVRNS4u

**Comment by jiawei2912** [comment]
**Update - 10 September 2020**
**Session Name:** Introductory Training for Systema (Russian Martial Arts)
**Status:** Approved
**Allowed Members:** 
- Lim Jin Feng, Nick
- Nurul Akhira Binte Zakaria

**Remarks:**
- Nil
