### ISSUE TITLE
[FRS] FUNKtion Intro!

### ISSUE THREAD

**Issue by yufan-fong** [OpenSUTD/DiscoverSUTD-2020#32]
**Session Name**

FUNKtion Intro!

**Abstract**

Come join us to find out more about locking and popping in funkstyle! You will be able to try out a few dance moves and find out what exactly is funkstyle!

**Student Organisation organising this Session**

FUNKtion

**Session Intent (What to Expect)**

Participants will be able to learn and try out *basic locking and popping moves.* They will find out more about funkstyle culture in Singapore.
Participants are not required to have any prior dance experience, just come with an open mind!

**Session Details**

These sessions will be on a sign-up basis. We would like to have our introductory sessions on Mondays and Thursdays of week 2 and 3 from 7pm-10pm at Dance Studio 3 or 4. For each day, we would like to have 3 50-minute sessions with 10 minute breaks to last from 7pm-10pm. For each session, freshmores will be placed into groups of 3 and attached to 2 FUNKtion members. The groupings and timings will be adjusted according to the response.

**Speakers/Workshop Facilitators**

The sessions will be conducted by our club members.

**Logistical Details**

We do not require additional logistics or budget from the DiscoverSUTD team. Our club email is funktion@club.sutd.edu.sg. Our sign-up form link is not ready yet.

**OSL** STATUS: APPROVED ✅

**Comment by jiawei2912** [comment]
**Update - 10 September 2020**
**Session Name:** FUNKtion Intro!
**Status:** Approved*
**Allowed Members:** 
- Chong Wah Jin Brandon
- Loi Xuan
- Kenneth Heng
- David Palcon Sioson
- Ryann Yeo Renren
- Fong Yu Fan
- Joshua Dean Samjaya
- Jeremy Wong Zhan Yik
- Chen Pengdan (Crystal)
- Feng Han (Hannah)


**Remarks:**
- Nil

**Comment by jiawei2912** [comment]
Update - 14 September 2020
Session Name: FUNKtion Intro!
Status: Approved
Remarks:
OSA is holding on to the bookings for both Dance Studio 3 and 4. FUNKtion can take over the use of Dance Studio 3 and 4 for their intro sessions.
