### ISSUE TITLE
[FRS] SUTD Civil Defence Lionhearters Introductory Session

### ISSUE THREAD

**Issue by jiayingpui** [OpenSUTD/DiscoverSUTD-2020#33]
**Session Name**

SUTD Civil Defence Lionhearters Introductory Session

**Abstract**

If you have passion for the community, come join us and find out the things we do! :D

**Student Organisation organising this Session**

SUTD Civil Defence Lionhearters' Club

**Session Intent (What to Expect)**

- Share with us what you hope your participants will take away from this session. (Participants will learn ...)
About *who we are*, *what we do* and hopefully they will be inspired to join us in future sessions. 

- Share with us if there are any prerequisites to make the most of this session. (Participants will require knowledge of ...)
No prior knowledge required! Everyone is welcome to join. 

**Session Details**

Let us know the number of participants you can handle and where you intend to hold it. (If you need a venue, do let us know what sort of venue would be ideal to book.) If you have any constraints on the timing or any other matters, do specify them as well. If the session is conducted virtually on an online video conferencing platform, do add the event's shareable URL/link.
Number of expected participants: 20-30 (the more the merrier)

Venue: Zoom, https://zoom.us/j/8421590379?pwd=WjJrKzN1a3hzVHBZNS9odlFDcHdNZz09 

Meeting ID: 842 159 0379 

Passcode: 2nsZLV 

Date/Time: 18 September 8-8.30pm

**Speakers/Workshop Facilitators**

Pui Jia Ying (Vice President)

**Logistical Details**

Budget: Not required.
Club Email: cdlh@club.sutd.edu.sg

**Comment by jiawei2912** [comment]
**Update - 10 September 2020**
**Status:** Approved
**Remarks:**
- Nil
