### ISSUE TITLE
[FRS] Mountaineering Info Session

### ISSUE THREAD

**Issue by keithtan13** [OpenSUTD/DiscoverSUTD-2020#34]
**Session Name**
Mountaineering Info Session

**Abstract**
Info session for freshies to learn about Mountaineering Club's schedule and plans

**Student Organisation organising this Session**
SUTD Mountaineering  

**Session Intent (What to Expect)**
We will be sharing our experiences going on the multiple trips we have organised over the years to show the Freshies what is in store for them if they were to join us.
We will also elaborate on the educational and recreational workshops (eg. Layering workshop, Paracord workshop) that we hold, as well as our membership requirements.
Participants will require no previous knowledge or skillset

**Session Details**
Number of participants: 30
Date & Time: 22 September 2020 (Tuesday), 8-9pm
Microsoft Teams Link: https://teams.microsoft.com/l/team/19%3ad204447a54a244cf8290f569725f5a39%40thread.tacv2/conversations?groupId=bfcb3ccc-7c0a-4469-99c1-c8e1311ee92e&tenantId=3476b776-e990-4f72-b950-62489831623d

**Speakers/Workshop Facilitators**
SUTD Mountaineering Exco Members (Previous and current)

**Logistical Details**
NIL

Club email address: mountaineering@club.sutd.edu.sg

**Comment by jiawei2912** [comment]
**Update - 10 September 2020**
**Status:** Approved
**Remarks:**
- Nil
