### ISSUE TITLE
[FRS] Get to Know SUTD Rotaract!

### ISSUE THREAD

**Issue by rotaractsutd** [OpenSUTD/DiscoverSUTD-2020#35]
**Session Name**
Get to know SUTD Rotaract!

**Abstract**
Have a passion for community service? Want to use your talents and skills to make a difference? Get to know what SUTD Rotaract has in store for you during this Introductory Session!

**Student Organisation organising this Session**
SUTD Rotaract Club 

**Session Intent (What to Expect)**
SUTD Rotaract Club focuses on our service to the community, the professional development of our Rotaractors and forging strong bonds amongst fellow Rotaractors.

You will get to learn more about the volunteering and leadership opportunities that Rotaract Club offers. From overseas CIP projects to STEM workshops for underprivileged children, hear from your seniors on what they have gained through their experience in SUTD Rotaract.

Everyone is welcome to this Introductory Session! Join us to find out how we can change the community together!

**Session Details**
Date: Thursday, 24 September 2020 (Week 2)
Time: 8.00 pm - 9.00 pm

Venue: ZOOM Meeting (link will be shared soon/ upon sign-up)
No. of participants: NO LIMIT

**Speakers/Workshop Facilitators**
Speakers for this Introductory Session include Rotaractors, EXCO members from SUTD Rotaract, and Rotarian(s).

**Logistical Details**
Event Sign-up Form:
https://forms.office.com/Pages/ResponsePage.aspx?id=drd2NJDpck-5UGJImDFiPT3mUKDTZCJAv7pi6JKUYT5URUNMQkxTQ1FYUjRQUkdTVFNJNzZQRUJRSy4u 

Club Email:
rotaract@club.sutd.edu.sg

**Comment by jiawei2912** [comment]
**Update - 10 September 2020**
**Status:** Approved
**Remarks:**
- Nil
