### ISSUE TITLE
[FRS] Introductory Session to Chinese Orchestra

### ISSUE THREAD

**Issue by sxy33** [OpenSUTD/DiscoverSUTD-2020#36]
**Session Name**
  > >Introductory session to Chinese Orchestra

A title that captures the intent of the session and is attention-grabbing.

**Abstract**
   >>To give a brief introduction to our Chinese Orchestra's background and different sections in the orchestra. Q&A session 
       is available.

A short description of the highlights of your session in one or two sentences.

**Student Organisation organising this Session**
   >>Chinese Orchestra

**Session Intent (What to Expect)**
 >>Participants will learn more about:
    Participants will learn more about:
    - Background and Achievements of SUTDCO
    - Structure of a Chinese Orchestra &  Basics of various Chinese instruments
    - Activities to look forward to in SUTDCO
    No pre-requisite knowledge required. All are welcome regardless of experience. We just need your passion for music :-)

- Share with us what you hope your participants will take away from this session. (Participants will learn ...)
- Share with us if there are any prerequisites to make the most of this session. (Participants will require knowledge of ...)
- *Italicise* the specific skills/takeaways that are quantifiable to help us create a concept map of the sessions we are offering for our incoming Freshmores.

**Session Details**
>>Intro session: 7:30-8:30PM
                            7:30-7:40: CO background Intro and self-introduction
                            7:40-7:50: Intro to Percussion instruments 
                            7:50-8:00: Intro to Winds instruments
                            8:00-8:10: Intro to Strings instruments
                            8:10-8:20: Intro to Plucking instruments 
                            8:20-8:30: Q&A
>> number of participants: unlimit 
>>venue: Music Room 1 (To conduct the video conferencing in mr1 and showcase instrument)
>>platform: Zoom: https://zoom.com.cn/j/92752629949?pwd=TWZSSkdvNVNyVnZLRWxqbUQ1ZjhRZz09

Let us know the number of participants you can handle and where you intend to hold it. (If you need a venue, do let us know what sort of venue would be ideal to book.) If you have any constraints on the timing or any other matters, do specify them as well. If the session is conducted virtually on an online video conferencing platform, do add the event's shareable URL/link.

**Speakers/Workshop Facilitators**
  >> SUTDCO members

Share with us the background of your facilitators to provide some context for your participants.

**Logistical Details**
   >>sign up form: https://forms.office.com/Pages/ResponsePage.aspx?id=drd2NJDpck-5UGJImDFiPVrVhVGgu2BJt8fOu-Z2Sf5UOEEySEFaQllLSEZBRTE0RFc4WFVCTkhRSC4u

Help us with the overall resourcing of our events. This will give us some cues on as to how to budget for the event and if there are further constraints that we must consider.
Please provide us with your club e-mail address so we can notify you once your event has been scheduled.
If your event is on a sign-up basis, also include your sign-up form link here. Copy [this template](https://forms.office.com/Pages/ShareFormPage.aspx?id=drd2NJDpck-5UGJImDFiPbne1iyIR1hKtYGeiPHQbEBUM0JEN0xMN041VFBZOU1aSjRVTzlTMzBISi4u&sharetoken=TEsfn8upjgncvVX6vj8Y) to ensure consistent branding throughout DiscoverSUTD.

**Comment by jamestiotio** [comment]
Hi, may I know what is the proposed date(s) for this event?

**Comment by jiawei2912** [comment]
**Update - 10 September 2020**
**Session Name:** Introductory session to Chinese Orchestra
**Status:** Approved
**Allowed Members:** 
- Tan Jian Hui
- Tan Kewen
- Chia Yu Ying
- Shang Xiangyuan
- Li Chenxi

**Remarks:**
- Access to Music Room 1 on 21 September is approved.

**Comment by jiawei2912** [comment]
Update - 14 September 2020
Session Name: Introductory session to Chinese Orchestra
Status: Approved
Allowed Members:
Remarks:
Security has programmed temporary card access for Xiangyuan, Tan Kewen, Yu Ying, Chenxi, and Jian Hui. They will need to tap their student card when entering Music Room 1 on 21 Sep

The venue usage is until from 1900 - 2300hrs. They may call 6303 6699 if there are any issues with access to the venue.
