### ISSUE TITLE
[FRS] Design Odyssey: Introduction and Induction to Design Innovation

### ISSUE THREAD

**Issue by DesignOdyssey** [OpenSUTD/DiscoverSUTD-2020#38]
**Session Name**

Design Odyssey: Introduction and Induction to Design Innovation

**Abstract**

Learn all about Design Odyssey’s DRIVE social innovation programme! Session includes a Design Innovation exercise, where students will learn design innovation and technical skills that are highly in-demand by the workforce.

**Student Organisation organising this Session**

Design Odyssey

**Session Intent (What to Expect)**

- Participants will learn about Design Odyssey’s Drive program, and the opportunities available to them to Discover, Define, Develop and Deliver their self-initiated Social Innovations from Ideation to Business Pitching. 

- Sharing from Past Participants and their startup success! 

- Students will get a chance to participate in a Micro Design Innovation exercise, where they will learn design innovation and technical skills that are highly in-demand by the workforce.

**Session Details**

Date: 18 September (Friday) 

Time: 2pm to 5pm (please log in 10mins prior to the start of the session) 

Venue: Zoom (details will be provided closer to the date of event)

**Speakers/Workshop Facilitators**

Ms. Sio Lim, Associate Program Director, Design Odyssey, SUTD-MIT International Design Centre (IDC) 

Ms. Ashreya M Venkatesh, Design Engineer, Design Odyssey, SUTD-MIT International Design Centre (IDC)

**Logistical Details**

Club’s Email Address: design_odysssey@sutd.edu.sg 

Participants’ Sign Up Form: https://forms.office.com/Pages/ResponsePage.aspx?id=drd2NJDpck-5UGJImDFiPUgJpuzDUOxPqL7bSCpRONZUQTNDQlNWME5UVTZNUjNXT1FDRko5UThZVS4u

**Comment by jiawei2912** [comment]
**Update - 10 September 2020**
**Status:** Approved*
**Remarks:**
- Nil
