### ISSUE TITLE
[FRS] Design Odyssey: Introduction & Business Model Workshop

### ISSUE THREAD

**Issue by DesignOdyssey** [OpenSUTD/DiscoverSUTD-2020#39]
**Session Name**

Design Odyssey: Introduction & Business Model Workshop

**Abstract**

Learn all about Design Odyssey’s DRIVE social innovation programme! Session includes Business Model exercise, where students will learn how to leverage on the Business model canvas as a strategic and management tool to describe, design and pivot a business!

**Student Organisation organising this Session**

Design Odyssey

**Session Intent (What to Expect)**

- Participants will learn about Design Odyssey’s Drive program, and the opportunities available to them to Discover, Define, Develop and Deliver their self-initiated _Social Innovations_ from _Ideation_ to _Business Pitching_. 

- Sharing by Past Participants and their startup success! 

- Students will get a chance to participate in a Business Model exercise, where they will learn how to leverage on the Business model canvas as a _strategic and management_ tool to describe, design and pivot a business.

**Session Details**

Date: 30 September (Wednesday) 

Time: 2pm to 5pm (please log in 10mins prior to the start of the session) 

Venue: Zoom (details will be provided closer to the date of event)

**Speakers/Workshop Facilitators**

Ms. Sio Lim, Associate Program Director, Design Odyssey, SUTD-MIT International Design Centre (IDC) 

Ms. Ashreya M Venkatesh, Design Engineer, Design Odyssey, SUTD-MIT International Design Centre (IDC)

**Logistical Details**

Club’s Email Address: design_odysssey@sutd.edu.sg 

Participants’ Sign Up Form: https://forms.office.com/Pages/ResponsePage.aspx?id=drd2NJDpck-5UGJImDFiPUgJpuzDUOxPqL7bSCpRONZUQTNDQlNWME5UVTZNUjNXT1FDRko5UThZVS4u

**Comment by jiawei2912** [comment]
**Update - 10 September 2020**
**Status:** Approved*
**Remarks:**
- Nil
