### ISSUE TITLE
[FRS] Dance DerivativeZ Info Sesh x Trials

### ISSUE THREAD

**Issue by yjtai97** [OpenSUTD/DiscoverSUTD-2020#41]
**Dance DerivativeZ Info Sesh x Freshie Trials**

Want to learn more about DDZ? Ever wanted to dance but didn't have the opportunity to try it out? Come down (on Zoom) for DDZ's trial sessions and learn if this is the fifth row for you! 👍

**Dance DerivativeZ**

**What to Expect**

Our trial sessions will encompass an info session, where you get to learn more about the club culture, get to know some of us, find out what we've done as a club and ask any questions, and a beginner-friendly dance segment where you get to experience what our sessions are like!

DDZ has a no-auditions policy, so if you always wanted to dance or thought dance was cool, come down, join us and have fun with us :) See you there! 💃🕺

**Important Information:**

- Dates: 16th September (Wednesday), 25th September (Friday), 30th September (Wednesday)

- Time: 7.00pm to 9.00pm on 16th Sept, 7.30pm to 10.00pm on 25th and 30th Sept
Timeline Breakdown:
7.30pm - 8pm: Info Session
8pm - 8.15pm: Break
8.15pm - 10pm: Actual dancing wuhu

- Zoom URL: https://us02web.zoom.us/j/81564316238?pwd=VWc1Y3RVcEU3UVRENHJ0YWZXa3kzdz09 (will be sent again on trial days in Telegram Group)

- Telegram group join link: https://t.me/DDZfreshies (join if you are coming for the sessions / have questions about the club / overall interested in DDZ!)

Follow us on Instagram @sutd_ddz and find us on Youtube at https://www.youtube.com/c/DanceDerivativeZ/featured 🔥
**Speakers/Workshop Facilitators**

Share with us the background of your facilitators to provide some context for your participants.

**Logistical Details**

All sessions will be organized on Zoom.
Contact us at: dancederivativez@club.sutd.edu.sg
Sign up form: https://forms.office.com/Pages/ResponsePage.aspx?id=drd2NJDpck-5UGJImDFiPYR1TTYbRMVPjUHSPr9V-UpURVVSSUcwTlM2RDhHWjBJWVdXQUg0RkdUMi4u

**Comment by jiawei2912** [comment]
**Update - 10 September 2020**
**Session Name:** Dance DerivativeZ Info Sesh x Freshie Trials
**Status:** Approved
**Allowed Members:** 
- Mark Tay

**Remarks:**
- Nil
