### ISSUE TITLE
[FRS] SUTD PhotogCircle Intro & Sharing Session

### ISSUE THREAD

**Issue by jamestiotio** [OpenSUTD/DiscoverSUTD-2020#42]
> _[Issue created on behalf of SUTD Photography Circle]_

**Session Name**

SUTD PhotogCircle Intro & Sharing Session

**Abstract**

Whether you are a complete beginner or a Nat-Geo level photographer, SUTD PhotogCircle might just be the place for you! Come join us on MS Teams to find out more in this short sharing session!

**Student Organisation organising this Session**

SUTD Photography Circle

**Session Intent (What to Expect)**

Short information sharing session on PhotogCircle, followed by a mini sharing session among participants on photography and recruitment drive.

**Session Details**

Date: 22 September 2020.
Timing: 7.30pm to 9.30pm.
Venue: Microsoft Teams Meeting.
Expected Turnout: 10-15.

**Speakers/Workshop Facilitators**

Phua Kai Jie (Co-organiser)

**Logistical Details**

Budget: Not required.

Club Email: photogcircle@club.sutd.edu.sg

> If your event is on a sign-up basis, also include your sign-up form link here. Copy [this template](https://forms.office.com/Pages/ShareFormPage.aspx?id=drd2NJDpck-5UGJImDFiPbne1iyIR1hKtYGeiPHQbEBUM0JEN0xMN041VFBZOU1aSjRVTzlTMzBISi4u&sharetoken=TEsfn8upjgncvVX6vj8Y) to ensure consistent branding throughout DiscoverSUTD.

**Comment by jiawei2912** [comment]
**Update - 10 September 2020**
**Status:** Approved
**Remarks:**
- Nil
