### ISSUE TITLE
[FRS] IEEE: Industry Talk

### ISSUE THREAD

**Issue by jamestiotio** [OpenSUTD/DiscoverSUTD-2020#43]
> _[Issue created on behalf of IEEE SUTD Student Branch]_

**Session Name**

Industry Talk

**Abstract**

Mr. Govind Kumar, Founder of SeaPort AI, will educate students on recent trends in analytics and how to become a full stack data scientist.

**Student Organisation organising this Session**

IEEE SUTD Student Branch

**Session Intent (What to Expect)**

Mr. Kumar will focus on providing more clarity in the following areas:

1. What is a full stack view? Why is it important to get a full stack view of data science?
2. Recent trends in data analytics.
3. Challenges encountered by data scientists and how to overcome them.

**Session Details**

Date: 25 September 2020.
Timing: 4pm to 6pm.
Venue: Zoom Meeting.
Expected Turnout: 100.
Target Audience: All SUTD students interested in data science.

**Speakers/Workshop Facilitators**

Mr. Govind Kumar, Founder of SeaPort AI.

**Logistical Details**

Budget: Not required.

Club Email: ieee@club.sutd.edu.sg

> If your event is on a sign-up basis, also include your sign-up form link here. Copy [this template](https://forms.office.com/Pages/ShareFormPage.aspx?id=drd2NJDpck-5UGJImDFiPbne1iyIR1hKtYGeiPHQbEBUM0JEN0xMN041VFBZOU1aSjRVTzlTMzBISi4u&sharetoken=TEsfn8upjgncvVX6vj8Y) to ensure consistent branding throughout DiscoverSUTD.

**Comment by jiawei2912** [comment]
**Update - 10 September 2020**
**Status:** Approved*
**Remarks:**
- Nil
