### ISSUE TITLE
[FRS] IEEE: Natural Language Processing (NLP) Workshop for Beginners

### ISSUE THREAD

**Issue by jamestiotio** [OpenSUTD/DiscoverSUTD-2020#44]
> _[Issue created on behalf of IEEE SUTD Student Branch]_

**Session Name**

IEEE: Natural Language Processing (NLP) Workshop for Beginners

**Abstract**

What is Natural Language Processing? What are chatbots? Come and join SUTD IEEE in exploring and building a basic architecture with NLP.

**Student Organisation organising this Session**

IEEE SUTD Student Branch

**Session Intent (What to Expect)**

To teach the incoming freshmen (Class of 2024) NLP and the links to their Term 1 Module: Computational Thinking for Design.

**Session Details**

Date: 16 September 2020.
Timing: 5pm to 7pm.
Venue: Microsoft Teams Meeting.
Expected Turnout: 100.

**Speakers/Workshop Facilitators**

Wu Xinyun (Software Lead of IEEE)

**Logistical Details**

Budget: Not required.

Club Email: ieee@club.sutd.edu.sg

> If your event is on a sign-up basis, also include your sign-up form link here. Copy [this template](https://forms.office.com/Pages/ShareFormPage.aspx?id=drd2NJDpck-5UGJImDFiPbne1iyIR1hKtYGeiPHQbEBUM0JEN0xMN041VFBZOU1aSjRVTzlTMzBISi4u&sharetoken=TEsfn8upjgncvVX6vj8Y) to ensure consistent branding throughout DiscoverSUTD.

**Comment by jiawei2912** [comment]
**Update - 10 September 2020**
**Status:** Approved*
**Remarks:**
- Nil
