### ISSUE TITLE
[FRS] Bandscamp 2020

### ISSUE THREAD

**Issue by jamestiotio** [OpenSUTD/DiscoverSUTD-2020#45]
> _[Issue created on behalf of SUTD Bands]_

**Session Name**

Bandscamp 2020

**Abstract**

Bandscamp 2020 is a 1-day online orientation for students interested in joining SUTD Bands, where we’ll introduce the club, our culture and notable events. There will also be icebreakers, workshops/tours and a mini project.

**Student Organisation organising this Session**

SUTD Bands

**Session Intent (What to Expect)**

To introduce SUTD Bands to incoming freshies (e.g. what the club is about, the events we organize) and to try to orientate potential club members.

**Session Details**

Date: 3 October 2020.
Timing: 3pm to 7.30pm.
Venue: Zoom Meeting.
Expected Turnout: 50.

- Filming of Jam Room Tour will be conducted on 19 September 2020, 1200-1700hrs which would involve 2 EXCO members at the Jam Room (Music Room).
- Online concert preparation will be conducted on 26 September 2020, where all digital submissions of seniors' projects will be collated and livestreaming on streaming site will be tested out.
- Freshie's Bands Showcase will be conducted on 10 October 2020 as an online concert on either Zoom or YouTube. From the end of Bandscamp 2020 until then, mentors will guide the freshie bands virtually and freshies would need to record their parts individually.

**Speakers/Workshop Facilitators**

SUTD Bands EXCO Members.

**Logistical Details**

Budget: Self-sourced.
Club Email: sutdbands@club.sutd.edu.sg

**OSL** STATUS: APPROVED ✅

> If your event is on a sign-up basis, also include your sign-up form link here. Copy [this template](https://forms.office.com/Pages/ShareFormPage.aspx?id=drd2NJDpck-5UGJImDFiPbne1iyIR1hKtYGeiPHQbEBUM0JEN0xMN041VFBZOU1aSjRVTzlTMzBISi4u&sharetoken=TEsfn8upjgncvVX6vj8Y) to ensure consistent branding throughout DiscoverSUTD.

**Comment by shohamc1** [comment]
As DiscoverSUTD ends on 2 October, we would not be able to support the session on 3rd October. Please chose a new date and inform us if you would like the event to be conducted under DiscoverSUTD.

**Comment by jiawei2912** [comment]
**Update - 10 September 2020**
**Status:** Rejected
**Remarks:**
- Proposed date is outside of the range of DiscoverSUTD
