### ISSUE TITLE
[FRS] Mindsports Online Intro Event

### ISSUE THREAD

**Issue by jamestiotio** [OpenSUTD/DiscoverSUTD-2020#46]
> _[Issue created on behalf of Mindsports]_

**Session Name**

Mindsports Online Intro Event

**Abstract**

- Play boardgames with your friends or make new ones.
- Talk about game development.

**Student Organisation organising this Session**

Mindsports

**Session Intent (What to Expect)**

Promote bonding among participants.

**Session Details**

Participants join Discord and filter into different Virtual Game rooms/voice channels.

Date: 22 September 2020.
Timing: 7pm to 9pm.
Venue: Discord.
Expected Turnout: 30.

**Speakers/Workshop Facilitators**

Mindsports EXCO Members.

**Logistical Details**

Budget: Not required.
Club Email: mindsports@club.sutd.edu.sg 

> If your event is on a sign-up basis, also include your sign-up form link here. Copy [this template](https://forms.office.com/Pages/ShareFormPage.aspx?id=drd2NJDpck-5UGJImDFiPbne1iyIR1hKtYGeiPHQbEBUM0JEN0xMN041VFBZOU1aSjRVTzlTMzBISi4u&sharetoken=TEsfn8upjgncvVX6vj8Y) to ensure consistent branding throughout DiscoverSUTD.

**Comment by jiawei2912** [comment]
**Update - 10 September 2020**
**Status:** Approved
**Remarks:**
- Nil
