### ISSUE TITLE
[FRS] Greenprint Introductory Sessions 2020

### ISSUE THREAD

**Issue by jamestiotio** [OpenSUTD/DiscoverSUTD-2020#47]
> _[Issue created on behalf of Greenprint]_

**Session Name**

Greenprint Introductory Sessions 2020

**Abstract**

Hi Freshmen! Are you passionate about the environment or want to know more? Look no further! SUTD Greenprint is the school’s environmental club. If you are looking for a group of people to discuss or work on environmental projects, then Greenprint is for you. Even if you’re just looking to meet new people, no worries as Greenprint welcomes all.

**Student Organisation organising this Session**

Greenprint

**Session Intent (What to Expect)**

To introduce incoming freshmen to SUTD Greenprint and serve as a recruitment drive for potential members or just make friends.

**Session Details**

Dates: 14 & 21 September 2020.
Timing: 7pm to 9.30pm.
Venue: Opportunity Lab (O Lab).
Expected Turnout: 15.

For pre-event at 1845hrs – 1900hrs and post-event at 2130hrs – 2145hrs, tables in the O Lab will be set up, cleaned up and disinfected.

4 groups of up to 4 freshmen each, with 1 senior tagged to each freshman group:
- Each freshman group will stay in one designated table of the O Lab at each time.
- Three-meters social distancing will be ensured in between groupings.
- Groups will be made identifiable through tables groups.

**Speakers/Workshop Facilitators**

Greenprint Club Members.

**Logistical Details**

Budget: Not required.
Club Email: greenprint@club.sutd.edu.sg

> If your event is on a sign-up basis, also include your sign-up form link here. Copy [this template](https://forms.office.com/Pages/ShareFormPage.aspx?id=drd2NJDpck-5UGJImDFiPbne1iyIR1hKtYGeiPHQbEBUM0JEN0xMN041VFBZOU1aSjRVTzlTMzBISi4u&sharetoken=TEsfn8upjgncvVX6vj8Y) to ensure consistent branding throughout DiscoverSUTD.

**Comment by jiawei2912** [comment]
Update - 15 September 2020
Status: Approved
List of approved personnel:

- Jaryl Lim
- Shaun Ha
- Lu Qianxi
- Selvam Shwetha
- Alice Cheong

Remarks:
-
