### ISSUE TITLE
[FRS] SOAR: Introduction to Arduino

### ISSUE THREAD

**Issue by jamestiotio** [OpenSUTD/DiscoverSUTD-2020#48]
> _[Issue created on behalf of SOAR]_

**Session Name**

Introduction to Arduino

**Abstract**

Participants learn how to program the Arduino and use certain electronic components.

**Student Organisation organising this Session**

SOAR

**Session Intent (What to Expect)**

To familiarize interested participants in the utilization of microcontrollers such as an Arduino, while teaching programming logic processes in C++. Participants will also learn how to use certain electronic components like resistors and transistors.

**Session Details**

Dates: 17, 24 September 2020 & 1 October 2020.
Timing: 7.30pm to 9.45pm.
Venue: Online.
Expected Turnout: 40.

For pre-event at 1900hrs – 1930hrs, instructors will set up lesson materials including slides, online handouts, and Arduino & electronics kits for online demo and prepare for exploratory learning with Arduino simulators.

For post-event, at 2200hrs - 2215hrs, instructors will clean up materials used for online demo.

**Speakers/Workshop Facilitators**

SOAR EXCO Members.

**Logistical Details**

Budget: Self-sourced.
Club Email: soar@club.sutd.edu.sg
Sign-Up Form: https://forms.office.com/Pages/ResponsePage.aspx?id=drd2NJDpck-5UGJImDFiPZ0x4lBoJ0FJp4ph0q2ywpVUNktDMk05MUxDRVRJRUc3Q0tCMUEzUFA3My4u

**Comment by jiawei2912** [comment]
**Update - 10 September 2020**
**Status:** Approved
**Remarks:**
- Nil
