### ISSUE TITLE
[FRS] Tchoukball Introductory Sessions 2020

### ISSUE THREAD

**Issue by jamestiotio** [OpenSUTD/DiscoverSUTD-2020#49]
> _[Issue created on behalf of Tchoukball]_

**Session Name**

Tchoukball Introductory Sessions 2020

**Abstract**

Hi Freshmen! Are you looking to join a Fifth Row with a tight-knit community and pick up an interesting new sport at the same time? Look no further! Join SUTD Tchoukball at our introductory sessions to learn more about Tchoukball and make new friends at the same time! No prior experience is needed!

**Student Organisation organising this Session**

Tchoukball

**Session Intent (What to Expect)**

To introduce incoming freshmen to SUTD Tchoukball as well as Tchoukball as a sport, and serve as a recruitment drive for potential members.

**Session Details**

Dates: 15, 17, 22 & 24 September 2020.
Timing: 8pm to 9.30pm.
Venue: ISH 1.
Expected Turnout: 80.

6 groups of 4 freshmen each, with 1 senior tagged to each freshman group:
- Each freshman group will stay in one designated area of the court at each time.
- Three-meters social distancing will be ensured in between groupings.
- Groups will not be allowed to have contact, whether direct or indirect (e.g. sharing of Tchoukballs).
- Gameplay will not take place amongst groups, only ball drills will be carried out within each group of 5.
- Groups will be made identifiable through different coloured T-shirts.
- Total number of people in the hall at any one time is 31, including our coach.
- The coach will also maintain a 3-meters social distancing from all groups at any time.

For pre-event, at 1930hrs - 2000hrs, the Tchoukball equipment will be set up and disinfected.
For post-event, at 2130hrs - 2145hrs, all equipment used by the freshmen groups will be cleaned up and disinfected.
Both pre-event and post-event will be conducted at the ISH Storeroom.

**Speakers/Workshop Facilitators**

Tchoukball Club Members.

**Logistical Details**

Budget: Not required.
Club Email: tchoukball@club.sutd.edu.sg

> If your event is on a sign-up basis, also include your sign-up form link here. Copy [this template](https://forms.office.com/Pages/ShareFormPage.aspx?id=drd2NJDpck-5UGJImDFiPbne1iyIR1hKtYGeiPHQbEBUM0JEN0xMN041VFBZOU1aSjRVTzlTMzBISi4u&sharetoken=TEsfn8upjgncvVX6vj8Y) to ensure consistent branding throughout DiscoverSUTD.

**Comment by shohamc1** [comment]
Hi, there is a mandatory Hostel briefing session on 15th September and would not be able to approve the event for that day. You and your team might want to either change the date for that particular session or work with the reduced number of sessions.

**Comment by jiawei2912** [comment]
**Update - 10 September 2020**
**Status:** In appeal
**Remarks:**
- Late submission of details

**Comment by jiawei2912** [comment]
Update - 15 September 2020
Status: Approved
List of approved personnel:

- Sumi Boo
- Shaun Ha
- Ken Zho Lim
- Ashwini Naidu

Remarks:
-

**Comment by jiawei2912** [comment]
**Update - 15 September 2020**
**Status:** Approved
**Remarks:**
- Session on the 15th shifted to the 29th.
