### ISSUE TITLE
[FRS] EV Club Introductory Session

### ISSUE THREAD

**Issue by jamestiotio** [OpenSUTD/DiscoverSUTD-2020#50]
> _[Issue created on behalf of Electric Vehicle Club]_

**Session Name**

EV Club Introductory Session

**Abstract**

An informative session to introduce EV Club to SUTD community (mainly Freshmores for recruitment) via Microsoft Teams.

**Student Organisation organising this Session**

Electric Vehicle Club

**Session Intent (What to Expect)**

This Microsoft Teams session will consist of an introduction to our club, what we do, and what they can expect if they join us. We will also make use of this time to present them the club’s roadmap.

**Session Details**

Date: 23 September 2020.
Timing: 8pm to 9pm.
Venue: Microsoft Teams Meeting.
Expected Turnout: 50.

**Speakers/Workshop Facilitators**

EV Club Members.

**Logistical Details**

Budget: Not required.
Club Email: ev@club.sutd.edu.sg

> If your event is on a sign-up basis, also include your sign-up form link here. Copy [this template](https://forms.office.com/Pages/ShareFormPage.aspx?id=drd2NJDpck-5UGJImDFiPbne1iyIR1hKtYGeiPHQbEBUM0JEN0xMN041VFBZOU1aSjRVTzlTMzBISi4u&sharetoken=TEsfn8upjgncvVX6vj8Y) to ensure consistent branding throughout DiscoverSUTD.

**Comment by jiawei2912** [comment]
**Update - 10 September 2020**
**Status:** Approved
**Remarks:**
- Nil

**Comment by kaitkj** [comment]
Noted with thanks!
