### ISSUE TITLE
[FRS] MVMC Online Information Session and Workshop

### ISSUE THREAD

**Issue by jamestiotio** [OpenSUTD/DiscoverSUTD-2020#51]
> _[Issue created on behalf of Modern Visual Media Circle]_

**Session Name**

MVMC Online Information Session and Workshop

**Abstract**

MVMC Information Session and Basic Drawing Workshop.

**Student Organisation organising this Session**

Modern Visual Media Circle

**Session Intent (What to Expect)**

To brief the Freshmores regarding the club’s activities and to teach them regarding basic drawing techniques.

**Session Details**

Date: 18 September 2020.
Timing: 7pm to 8.45pm.
Venue: Online.
Expected Turnout: 20.

For pre-event, at 1830hrs – 1900hrs, the workshop materials will be prepared and the online meeting will be set up.

**Speakers/Workshop Facilitators**

Li Tianshu (project director and workshop instructor).

**Logistical Details**

Budget: Not required.
Club Email: mvmc@club.sutd.edu.sg

> If your event is on a sign-up basis, also include your sign-up form link here. Copy [this template](https://forms.office.com/Pages/ShareFormPage.aspx?id=drd2NJDpck-5UGJImDFiPbne1iyIR1hKtYGeiPHQbEBUM0JEN0xMN041VFBZOU1aSjRVTzlTMzBISi4u&sharetoken=TEsfn8upjgncvVX6vj8Y) to ensure consistent branding throughout DiscoverSUTD.

**Comment by jiawei2912** [comment]
**Update - 10 September 2020**
**Status:** Approved
**Remarks:**
- Nil
