### ISSUE TITLE
[FRS] SUTD Judo Online Sessions

### ISSUE THREAD

**Issue by jamestiotio** [OpenSUTD/DiscoverSUTD-2020#52]
> _[Issue created on behalf of SUTD Judo]_

**Session Name**

SUTD Judo Online Sessions

**Abstract**

Come join the SUTD Judo team for an online get-together! Ask questions, learn more about judo as a sport and as a Fifth Row!

**Student Organisation organising this Session**

SUTD Judo

**Session Intent (What to Expect)**

Sharing session, Judo videos, general Q&A, games.

- Share with us what you hope your participants will take away from this session. (Participants will learn ...)

Fun! Learning more about Judo! A new Fifth Row!

- Share with us if there are any prerequisites to make the most of this session. (Participants will require knowledge of ...)

Interest.

- *Italicise* the specific skills/takeaways that are quantifiable to help us create a concept map of the sessions we are offering for our incoming Freshmores.

NIL.

**Session Details**

Dates: 12 & 13 September 2020.
Timing: 8pm to 10pm.
Venue: [Discord](https://discord.gg/rYKm933).

**Speakers/Workshop Facilitators**

SUTD Judo EXCO, current members and alumni.

**Logistical Details**

Budget: Not required.
Club Email: judo@club.sutd.edu.sg

> If your event is on a sign-up basis, also include your sign-up form link here. Copy [this template](https://forms.office.com/Pages/ShareFormPage.aspx?id=drd2NJDpck-5UGJImDFiPbne1iyIR1hKtYGeiPHQbEBUM0JEN0xMN041VFBZOU1aSjRVTzlTMzBISi4u&sharetoken=TEsfn8upjgncvVX6vj8Y) to ensure consistent branding throughout DiscoverSUTD.

**Comment by shohamc1** [comment]
As DiscoverSUTD start on 15 September, we would not be able to support the sessions on 12th and 13th September. Please chose a new date and inform us if you would like the event to be conducted under DiscoverSUTD.

**Comment by jiawei2912** [comment]
**Update - 10 September 2020**
**Status:** In appeal
**Remarks:**
- In discussion with OSA about the shifting of dates

**Comment by jiawei2912** [comment]
Update - 15 September 2020
Status: Approved
Remarks:
- Date shifted to 19 and 20 of September 2020.
