### ISSUE TITLE
[FRS] SUTKD Introductory Session

### ISSUE THREAD

**Issue by jamestiotio** [OpenSUTD/DiscoverSUTD-2020#53]
> _[Issue created on behalf of SUTKD (Taekwondo)]_

**Session Name**

SUTKD Introductory Session

**Abstract**

Have you heard of but never experienced Taekwondo? Come have your first experience with us as we go through some basic ideas of self-defence through Taekwondo and the basic intentions behind Taekwondo!

**Student Organisation organising this Session**

SUTKD (Taekwondo)

**Session Intent (What to Expect)**

- Workshop participants will learn some basic principles behind self-defence, the intention of Taekwondo, and potentially a few basic self-defence techniques. 
- No prior experience required, but any is welcome. 
- To train a better sense of how the body moves and can be leveraged. 

**Session Details**

- No of participants: 2 groups of max 5 pax 
- Venue: Dance Studio 7 
- Timing: 18/09/2020 and 23/09/2020, 6pm to 8pm 

For pre-event and post-event, equipment and mats will be cleaned up and wiped using antiseptic wipes.

**Speakers/Workshop Facilitators**

- SUTKD Members 
- SUTKD Coach* (TBC) 

**Logistical Details**

Budget: Self-sourced.
Club Email: sutkd@club.sutd.edu.sg
Sign-Up Form: https://forms.office.com/Pages/ResponsePage.aspx?id=drd2NJDpck-5UGJImDFiPcSGqek7B_pMgh9iFJ0OSoZUQkJMN0VQREdWSE5EVVBRM1pWRjZNRVRJTi4u

**Comment by jiawei2912** [comment]
**Update - 10 September 2020**
**Session Name:** SUTKD Introductory Session
**Status:** Approved
**Allowed Members:** 
- Chua Jia Wei
- Leong Yun Qin Melody

**Remarks:**
- Nil
