### ISSUE TITLE
[FRS] Basketball Introductory 2v2 Tournament

### ISSUE THREAD

**Issue by jamestiotio** [OpenSUTD/DiscoverSUTD-2020#54]
> _[Issue created on behalf of SUTD Basketball Club]_

**Session Name**

Basketball Introductory 2v2 Tournament

**Abstract**

The basketball club will be hosting an introductory 2v2 tournament for the freshies to garner their interest for the club. This time will also be used to answer any queries that they may have about the club and at the same time have fun while enjoying the sport of basketball with their peers.

**Student Organisation organising this Session**

SUTD Basketball Club

**Session Intent (What to Expect)**

- Freshmore students to discover more about the Basketball Club and the sport itself.
- A fun game of basketball during the evening to take their mind off school.
- Freshmores who join this session will be able to interact and socialise more with their schoolmates and learn more about the meaning of teamwork.

**Session Details**

The Basketball Club intends to host this session in Indoor Sports Hall 1 (ISH1) on the 21st of September from 7-10pm and expects to have around 15 Freshmore students who will be willing to participate.

**Speakers/Workshop Facilitators**

The Basketball Club team members as well as our coach will be facilitating the event on the day itself.

**Logistical Details**

No extra logistics is required other than the availability of ISH1 (or ISH2 if ISH1 is occupied during the same timeframe) basketball court.
Club Email: basketball@club.sutd.edu.sg

> If your event is on a sign-up basis, also include your sign-up form link here. Copy [this template](https://forms.office.com/Pages/ShareFormPage.aspx?id=drd2NJDpck-5UGJImDFiPbne1iyIR1hKtYGeiPHQbEBUM0JEN0xMN041VFBZOU1aSjRVTzlTMzBISi4u&sharetoken=TEsfn8upjgncvVX6vj8Y) to ensure consistent branding throughout DiscoverSUTD.

**Comment by jiawei2912** [comment]
**Update - 10 September 2020**
**Status:** In appeal
**Remarks:**
- Late submission of details

**Comment by jiawei2912** [comment]
Update - 15 September 2020
Status: Approved
List of approved personnel:

- Tan Eng Khang
- Hoo Yon Wei, Gerald
- Max Lee Kang Bin
- Janus Wayne Enclona
- Jia Shuyi

Remarks:
-
