### ISSUE TITLE
[FRS] Karate Introduction Workshop

### ISSUE THREAD

**Issue by jamestiotio** [OpenSUTD/DiscoverSUTD-2020#55]
> _[Issue created on behalf of SUTD Karate Club]_

**Session Name**

Karate Introduction Workshop

**Abstract**

An introductory workshop for Freshmores to try out karate and to increase awareness and equip participants with basic knowledge and basic moves of karate.

**Student Organisation organising this Session**

SUTD Karate Club

**Session Intent (What to Expect)**

To promote karate as a sport and its culture, provide an opportunity for students, especially the Freshmores, and staff to enjoy martial arts and attract like-minded people to join our community.

**Session Details**

Dates: 22 & 29 September 2020.
Timing: 7.30pm to 9.30pm.
Venue: Dance Studios 6 & 7.
Expected Turnout: 5.
Target audience is SUTD students (Freshmores) and staff.

**Speakers/Workshop Facilitators**

Karate Club EXCO Members.

**Logistical Details**

Budget: Self-sourced.
Club Email: karate@club.sutd.edu.sg 

> If your event is on a sign-up basis, also include your sign-up form link here. Copy [this template](https://forms.office.com/Pages/ShareFormPage.aspx?id=drd2NJDpck-5UGJImDFiPbne1iyIR1hKtYGeiPHQbEBUM0JEN0xMN041VFBZOU1aSjRVTzlTMzBISi4u&sharetoken=TEsfn8upjgncvVX6vj8Y) to ensure consistent branding throughout DiscoverSUTD.

**Comment by jiawei2912** [comment]
**Update - 10 September 2020**
**Session Name:** Karate Introduction Workshop
**Status:** Approved
**Allowed Members:** 
- Yu Peijia
- Guo Yuchen

**Remarks:**
-Nil

**Comment by SapphireYX** [comment]
to be added, participants' sign up link: https://forms.office.com/Pages/ResponsePage.aspx?id=drd2NJDpck-5UGJImDFiPbhsKQzvkm1BtPVJIPA0FeVURTE0VUc4V1VXSzFUNEc4TFZPMUlaNUlYRS4u

**Comment by jiawei2912** [comment]
Update - 14 September 2020
Session Name: Karate Introduction Workshop
Status: Approved
Remarks:
OSL has booked dance studio 6 and 7 for Karate.
-Nil
