### ISSUE TITLE
[FRS] IES Intro & Sharing Session

### ISSUE THREAD

**Issue by KiranM27** [OpenSUTD/DiscoverSUTD-2020#58]
**Session Name**

IES Intro & Sharing Session

**Abstract**

If you are a career-driven individual who would like to enhance your skills by actively participating in workshops and working on interesting projects outside your coursework, come join us on MS Teams to find out more in this short sharing session!

**Student Organisation organising this Session**

IES Student Chapter @ SUTD

**Session Intent (What to Expect)**

Short information sharing session on the IES Student Chapter as well as the parent organization, followed by the mini sharing session among the participants.

**Session Details**

Date: 30th September 2020 (Wednesday)
Timing: 7:30 PM to 8:00 Pm
Venue: Microsoft Teams
Expected Turnout: 50

**Speakers/Workshop Facilitators**

IES Ex-co members

**Logistical Details**

Budget: Not Required
Club Email: ies@club.sutd.edu.sg
Participants' Sign Up Form: https://forms.office.com/Pages/ResponsePage.aspx?id=drd2NJDpck-5UGJImDFiPRn3dXOjm4FEsc0Wdt5VP6ZUMldCSVlVUk5WWDdOMEtKVUU0Vk5MMVhKMy4u

**Comment by jiawei2912** [comment]
**Update - 10 September 2020**
**Status:** Approved
**Remarks:**
- Nil
