### ISSUE TITLE
[FRS] Squash Intro Session

### ISSUE THREAD

**Issue by justinehy** [OpenSUTD/DiscoverSUTD-2020#99]
**Session Name**

Introductory Session to Squash

**Abstract**

Join us for our Introductory session to Squash! Squash is a lesser-known sport, but it is a fun, satisfying and yet challenging game. Participants will be introduced to the basics of Squash, and feel experience the physical, technical and social aspects of the sport. No prior experience is needed, our club consists of player of all skill levels!

**Student Organisation organising this Session**

SUTD Squash

**Session Intent (What to Expect)**

Learning some Fundamentals of Squash:
- Learn the rules of the game
- Learn the basic techniques of Squash
- Experience of playing the sport
- Experience the social nature of squash, get to know some friends and seniors!

Prerequisites:
- Be in Sports Attire
- (Preferably) Indoor court shoes
- No need to bring your own racket, but will be good if you have your own!
- No squash experience needed

**Session Details**

Let us know the number of participants you can handle and where you intend to hold it. (If you need a venue, do let us know what sort of venue would be ideal to book.) If you have any constraints on the timing or any other matters, do specify them as well. If the session is conducted virtually on an online video conferencing platform, do add the event's shareable URL/link.

No. of Participants: 10 - 16 per session (including facilitators)
Venue: Squash courts 1 & 2
Dates: 15 & 16 September (Tuesday & Wednesday)
Time: 7PM to 10PM

**Speakers/Workshop Facilitators**

Exco / Previous exco members will be facilitating the sessions, and to guide the participants along in getting to know Squash.

**Logistical Details**

No additional budget required. Rackets and balls will be provided by the squash club.

Club email:
squash@club.sutd.edu.sg

Sign up form:
https://forms.office.com/Pages/ResponsePage.aspx?id=drd2NJDpck-5UGJImDFiPVLNeLLHMHBHhZZxJujeCIBUN0s3SFBPSko0OVIzMUkwWklJWEdNVDkxRS4u

**Comment by jamestiotio** [comment]
Hi @justinehy!

Are you planning to conduct a Fifth Row Session for DiscoverSUTD 2021?

This repository was used for DiscoverSUTD 2020. For DiscoverSUTD 2021, please open a new issue at [this repository](https://github.com/OpenSUTD/DiscoverSUTD-2021-microsite/issues) instead.

If nothing else, I will be closing this issue since this issue is irrelevant.

Thank you!
